### ISSUE TITLE
kv_client_table_test should init KVClientTable<Val> with type double

### ISSUE THREAD

**Issue by RickAi** [TatianaJin/csci5570#4]
In the base/abstract_partition_manager.hpp, KVPairs was defined as `std::pair<third_party::SArray<Key>, third_party::SArray<double>>`, where the value is a SArray contains double type values.

In the worker/kv_client_table_test.cpp, the Add test init KVClientTable<Val> with type float, during the runtime, when kv_client_table try to call `partition_manager_->Slice(std::make_pair(keys, vals), &sliced);`, it will cause error because there will be a conflit between the float and double type value.

**Comment by TatianaJin** [comment]
Thanks for reporting the error. 

Yes, for simplicity you can change `float` to `double` in the kv_client_table_test.cpp. Or you may change the abstract_partition_manager to allow different types. If a certain type is to be used, say `double`, you may even remove the template for classes like KVClientTable, etc.

It is hard to tell which is better, which is why the problem remains here since last year. Do you think it is better for me to make changes to the codes, for the sake of simplicity?

**Comment by RickAi** [comment]
Personally, I think simply change the float to double while initialize kv_client_table will be better,  it will not cause lots of change in the project, and enough to satisfy the current training requirement. 

In the future when kv_client_table need support different type of values, we can change the KVPairs to a general pair type.

I will send a pull request if you agree too.

**Comment by TatianaJin** [comment]
Sounds reasonable. Please do so!
